-- Create songs table
create table if not exists public.songs (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  artist text,
  url text not null,
  uploader text,
  created_at timestamptz default now()
);

-- Create photos table
create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  image_urls text[] not null,
  description text,
  date timestamptz,
  uploader text,
  created_at timestamptz default now()
);

-- Create messages table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  text text not null,
  date timestamptz,
  sender text,
  created_at timestamptz default now()
);

-- Create blessings table
create table if not exists public.blessings (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now()
);

-- Create settings table
create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  name1 text,
  avatar1 text,
  password1_hash text,
  name2 text,
  avatar2 text,
  password2_hash text,
  start_date text,
  admin_password text,
  created_at timestamptz default now()
);

-- Enable Realtime for these tables
alter publication supabase_realtime add table public.songs;
alter publication supabase_realtime add table public.photos;
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.blessings;
alter publication supabase_realtime add table public.settings;

-- Enable RLS (Row Level Security) but allow public access for this simple app
-- You might want to restrict this in production
alter table public.songs enable row level security;
create policy "Public songs access" on public.songs for all using (true) with check (true);

alter table public.photos enable row level security;
create policy "Public photos access" on public.photos for all using (true) with check (true);

alter table public.messages enable row level security;
create policy "Public messages access" on public.messages for all using (true) with check (true);

alter table public.blessings enable row level security;
create policy "Public blessings access" on public.blessings for all using (true) with check (true);

alter table public.settings enable row level security;
create policy "Public settings access" on public.settings for all using (true) with check (true);
