-- Create visited_places table
create table if not exists public.visited_places (
  id bigint generated by default as identity primary key,
  name text not null unique, -- e.g. '天津', '北京', '广东' - Must match ECharts map names
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.visited_places enable row level security;

-- Policies (Allow public read, authenticated write)
create policy "Public read access"
on public.visited_places for select
using (true);

create policy "Public insert access"
on public.visited_places for insert
with check (true); -- For demo purposes, allowing public insert. In prod, restrict to authenticated.

create policy "Public delete access"
on public.visited_places for delete
using (true);

-- Enable Realtime
alter publication supabase_realtime add table public.visited_places;

-- Insert initial data (Tianjin)
insert into public.visited_places (name) values ('天津') on conflict (name) do nothing;
